project_name: podump

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: kubectl-podump
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: fnzv
    name: podump

krews:
  - name: podump
    repository:
      owner: fnzv
      name: krew-index
    directory: plugins
    homepage: https://github.com/fnzv/podump
    short_description: Dump pod logs and specs
    description: |
      A command-line tool to quickly export Kubernetes pod 
      specifications and logs to local files for debugging.
    caveats: |
      Usage:
        kubectl podump [pod-name]
    
    platforms:
      - selector:
          matchLabels:
            os: darwin
            arch: amd64
        bin: kubectl-podump
      - selector:
          matchLabels:
            os: darwin
            arch: arm64
        bin: kubectl-podump
      - selector:
          matchLabels:
            os: linux
            arch: amd64
        bin: kubectl-podump
      - selector:
          matchLabels:
            os: linux
            arch: arm64
        bin: kubectl-podump
      - selector:
          matchLabels:
            os: windows
            arch: amd64
        bin: kubectl-podump.exe